# Generated by Django 3.1.5 on 2021-05-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('rut', models.IntegerField()),
                ('direccion', models.CharField(max_length=40)),
                ('sitioweb', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Distribuidores',
            },
        ),
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('origen', models.CharField(max_length=40)),
                ('stock', models.IntegerField()),
                ('foto', models.ImageField(upload_to='imagenes')),
                ('tipo', models.CharField(choices=[('wh', 'whisky'), ('ce', 'cerveza'), ('vi', 'vino'), ('li', 'licor')], default='vi', max_length=2)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bebidas.distribuidor')),
            ],
            options={
                'verbose_name_plural': 'Bebidas',
            },
        ),
    ]
