# Generated by Django 3.1.5 on 2021-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebidas',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bebidas',
            name='precio',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='bebidas',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='sitioweb',
            field=models.URLField(blank=True),
        ),
    ]
