# Generated by Django 3.1.5 on 2021-05-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0003_distribuidor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribuidor',
            name='foto',
            field=models.ImageField(upload_to='imagenes'),
        ),
    ]
